### ISSUE TITLE
CLI Error 

### ISSUE THREAD

**Issue by jaasaria** [ionictheme/ionic4-start-theme#1]
![err2](https://user-images.githubusercontent.com/5240819/44501494-fab60f80-a6bf-11e8-9d03-d161de59cd2e.png)

After update / installing all the dependencies , still receiving this error. Please kindly check the attach file. thanks

**Comment by gopalvenu033** [comment]
![screenshot 43](https://user-images.githubusercontent.com/17723238/46527367-a0a78d00-c8ae-11e8-994b-fbb0c2b16238.png)
I have the above error when serve command loads.
following information shows using ionic info
Ionic:

   ionic (Ionic CLI)          : 4.2.0 
   Ionic Framework            : not installed
   @angular-devkit/core       : not installed
   @angular-devkit/schematics : not installed
   @angular/cli               : not installed
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
