### ISSUE TITLE
Tests not running after update to Angular 15

### ISSUE THREAD

**Issue by raranguren** [ionictheme/ionic4-start-theme#15]
- Steps to reproduce: `ng test`
- Expected behavior: `Executed 23 of 23 SUCCESS`
- Actual behavior: `Uncaught TypeError: __webpack_require__(...).context is not a function`

**Comment by raranguren** [comment]
Proposed solution in here:
https://github.com/firminoweb/ionic-start-theme/pull/16/commits/8275a1c693a317a652e2795fec8f14525d05aa42

**Comment by firminoweb** [comment]
I will rework it to a new version, and this issue will no longer exist, thank you.

**Comment by firminoweb** [comment]
I will rework it to a new version, and this issue will no longer exist, thank you.
