### ISSUE TITLE
Theme not installed correctly

### ISSUE THREAD

**Issue by gopalvenu033** [ionictheme/ionic4-start-theme#2]
![screenshot 43](https://user-images.githubusercontent.com/17723238/46527640-75716d80-c8af-11e8-807f-dd903ca09ffa.png)
I have the above error when serve command loads.
The following information shows when loading ionic info command in the theme root folder
Ionic:

   ionic (Ionic CLI)          : 4.2.0 
   Ionic Framework            : not installed
   @angular-devkit/core       : not installed
   @angular-devkit/schematics : not installed
   @angular/cli               : not installed
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by firminoweb** [comment]
Has you tried run $ ionic doctor check to see any module issue?

This current version are in Alpha version, i'm updating to latest beta version and some more critical improvements :)

**Comment by firminoweb** [comment]
Already up to date to final version of Ionic 4! 

I trust all Alpha, Beta and RC issues were fixed.
