### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by sharethemagics** [ionictheme/ionic4-start-theme#6]
When running the app in Ionic lab mode, I am getting the below error. 

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8200/build/app/app.esxgusf8.js

The app runs file in regular web mode.

**Comment by firminoweb** [comment]
Hi! sorry my late to reply.
This is a common issue and the error is about the Ionic Lab modules cache, i have publish an article about this and how to fix.

https://ionictheme.com/ionic4-workaround-ioniclab-blackscreen-error/
