### ISSUE TITLE
Error with new CodeSandbox version

### ISSUE THREAD

**Issue by iwilfried** [ionictheme/ionic4-start-theme#7]
DependencyNotFoundError
Could not find dependency: '@angular/compiler' relative to '/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js'
Suggested solutions:
Add @angular/compiler as dependency
▶ 11 stack frames were collapsed.
evaluate
main.ts:2
  1 | import { enableProdMode } from '@angular/core';
> 2 | import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
  3 | 
  4 | import { AppModule } from './app/app.module';
  5 | import { environment } from './environments/environment';

**Comment by firminoweb** [comment]
In few days i'm releasing a new version with all modules updated! and bug fixies :)

**Comment by iwilfried** [comment]
Hi Joao,

thanks for the message. I'm excited to see your updated work

All the best
Wilfried

**Comment by lucusapp** [comment]
Hi. I still have the same error. I would like to know if this problem is solved or if some additional configuration is required. Thank you
