### ISSUE TITLE
Compile  Error

### ISSUE THREAD

**Issue by AltRoot17** [ionictheme/ionic4-start-theme#8]
Dear,
When I run the project,I faced the fowling error,
any solution for this?

```
[ng] ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
[ng] node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
[ng] node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
[ng] node_modules/rxjs/internal/types.d.ts(82,52): error TS1005: ';' expected.
[ng] node_modules/rxjs/internal/types.d.ts(82,88): error TS1005: ';' expected.
[ng] node_modules/rxjs/internal/types.d.ts(82,92): error TS1109: Expression expected.
```

**Comment by vksingh225** [comment]
Same issue is with me too.

**Comment by Nuajan** [comment]
same here

**Comment by firminoweb** [comment]
In few days i'm releasing a new version with all modules updated! and bug fixies :)

**Comment by lawchihon** [comment]
> In few days i'm releasing a new version with all modules updated! and bug fixies :)

I don't see the new version, did I miss something?

**Comment by gustalitro** [comment]
Creo que no se publico nunca la nueva versión?, me hubiera gustado probar esta APP como mi primer proyecto
